# usage: ./server <server-port-number>
# usage: ./client <server-ip-address> <server-port-number>
all:
	g++ client.cpp -o client
	g++ server.cpp -o server
server:
	g++ server.cpp -o server
client:
	g++ client.cpp -o client
clean:
	rm server
	rm client
